import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Loader2, Plus, Pencil, Power, Save, X } from "lucide-react";
import { PageHeader, PageShell } from "@/components/page-shell";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/services")({ component: AdminServices });
const empty={name:"",slug:"",platform:"tiktok",price_per_unit:"0.01",min_quantity:"100",max_quantity:"10000"};
function AdminServices(){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const load=async()=>{const{data,error}=await supabase.from("services").select("id,name,slug,platform,is_active,price_per_unit,min_quantity,max_quantity").order("created_at",{ascending:false});if(error)toast.error(error.message);setRows(data??[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const save=async()=>{if(!form.name||!form.slug)return toast.error("أدخل اسم الخدمة والـslug");setSaving(true);const payload={name:form.name,slug:form.slug,platform:form.platform,price_per_unit:Number(form.price_per_unit),min_quantity:Number(form.min_quantity),max_quantity:Number(form.max_quantity)};const q=editing?supabase.from("services").update(payload).eq("id",editing):supabase.from("services").insert({...payload,is_active:true});const{error}=await q;setSaving(false);if(error)return toast.error(error.message);toast.success(editing?"تم تعديل الخدمة":"تم نشر الخدمة");setForm(empty);setEditing(null);await load()};
 const toggle=async(x:any)=>{const{error}=await supabase.from("services").update({is_active:!x.is_active}).eq("id",x.id);if(error)toast.error(error.message);else await load()};
 return <PageShell><PageHeader eyebrow="الإدارة" title="الخدمات والمنتجات" description="إضافة ونشر وتعديل وتعطيل خدمات السوشيال ميديا."/><div className="mx-auto max-w-7xl px-4 py-8"><div className="surface-card rounded-2xl p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{editing?"تعديل الخدمة":"إضافة خدمة جديدة"}</h2>{editing&&<Button variant="ghost" onClick={()=>{setEditing(null);setForm(empty)}}><X/>إلغاء</Button>}</div><div className="grid gap-3 md:grid-cols-3"><Input placeholder="اسم الخدمة" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input placeholder="slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><Input placeholder="المنصة" value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}/><Input type="number" step="0.0001" placeholder="السعر/وحدة" value={form.price_per_unit} onChange={e=>setForm({...form,price_per_unit:e.target.value})}/><Input type="number" placeholder="الحد الأدنى" value={form.min_quantity} onChange={e=>setForm({...form,min_quantity:e.target.value})}/><Input type="number" placeholder="الحد الأقصى" value={form.max_quantity} onChange={e=>setForm({...form,max_quantity:e.target.value})}/></div><Button className="mt-4" variant="hero" onClick={()=>void save()} disabled={saving}>{saving?<Loader2 className="animate-spin"/>:editing?<Save/>:<Plus/>}{editing?"حفظ التعديل":"نشر الخدمة"}</Button></div><div className="mt-6 space-y-3">{loading?<Loader2 className="mx-auto animate-spin"/>:rows.map(x=><div key={x.id} className="surface-card flex flex-wrap items-center justify-between gap-4 rounded-2xl p-5"><div><b>{x.name}</b><p className="text-muted-foreground text-xs">{x.platform} · {x.slug} · {x.price_per_unit}/وحدة</p></div><span>{x.is_active?"منشورة":"متوقفة"}</span><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setEditing(x.id);setForm({...x,price_per_unit:String(x.price_per_unit),min_quantity:String(x.min_quantity),max_quantity:String(x.max_quantity)})}}><Pencil/>تعديل</Button><Button size="sm" variant="outline" onClick={()=>void toggle(x)}><Power/>{x.is_active?"إيقاف":"نشر"}</Button></div></div>)}</div></div></PageShell>}
