import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { Loader2 } from "lucide-react";
import { PageHeader,PageShell } from "@/components/page-shell";
import { supabase } from "@/integrations/supabase/client";
import { money } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
export const Route=createFileRoute("/admin/orders")({component:AdminOrders});
const statuses=["pending","paid","processing","completed","cancelled","refunded"];
function AdminOrders(){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null);const load=async()=>{const{data,error}=await supabase.from("orders").select("id,user_id,status,quantity,total_price,target_input,extra_note,created_at").order("created_at",{ascending:false});if(error)toast.error(error.message);setRows(data??[]);setLoading(false)};useEffect(()=>{void load()},[]);const setStatus=async(id:string,status:string)=>{setBusy(id);const{error}=await supabase.rpc("admin_set_order_status",{_order_id:id,_status:status,_admin_note:null});setBusy(null);if(error)return toast.error(error.message);toast.success("تم تحديث حالة الطلب");await load()};return <PageShell><PageHeader eyebrow="الإدارة" title="الطلبات" description="عرض جميع الطلبات وتحديث حالتها من لوحة الإدارة."/><div className="mx-auto max-w-7xl px-4 py-8">{loading?<Loader2 className="mx-auto animate-spin"/>:<div className="space-y-3">{rows.map(r=><div key={r.id} className="surface-card rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><b>#{r.id.slice(0,8)}</b><p className="text-muted-foreground text-xs">العميل: {r.user_id} · {r.quantity} وحدة</p><p className="text-muted-foreground mt-1 text-xs">{r.target_input||"بدون هدف"}</p></div><strong>{money(r.total_price)}</strong></div><div className="mt-4 flex flex-wrap gap-2">{statuses.map(s=><Button key={s} size="sm" variant={r.status===s?"hero":"outline"} disabled={busy===r.id||r.status===s} onClick={()=>void setStatus(r.id,s)}>{busy===r.id&&r.status!==s?<Loader2 className="animate-spin"/>:s}</Button>)}</div></div>)}</div>}</div></PageShell>}
