import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { ClipboardList,Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader,PageShell } from "@/components/page-shell";
import { supabase } from "@/integrations/supabase/client";
import { dateAr,money,num } from "@/lib/format";
export const Route=createFileRoute("/dashboard/orders")({head:()=>({meta:[{title:"طلباتي | ViralHub"}]}),component:OrdersPage});
function OrdersPage(){const[orders,setOrders]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{let a=true;(async()=>{const{data:user}=await supabase.auth.getUser();if(!user.user){window.location.href="/login";return}const{data}=await supabase.from("orders").select("id,order_number,status,quantity,total_price,created_at,service_name,platform").eq("user_id",user.user.id).order("created_at",{ascending:false});if(a){setOrders(data??[]);setLoading(false)}})();return()=>{a=false}},[]);return <PageShell><PageHeader eyebrow="حسابي" title="طلباتي" description="سجل الطلبات وحالتها الحالية."/><div className="mx-auto max-w-5xl px-4 py-10">{loading?<div className="flex justify-center py-20"><Loader2 className="animate-spin"/></div>:orders.length===0?<div className="surface-card rounded-3xl p-10 text-center"><ClipboardList className="text-primary mx-auto mb-4 size-10"/><h2 className="text-xl font-bold">لا توجد طلبات بعد</h2><Button className="mt-5" variant="hero" asChild><Link to="/services">تصفح الخدمات</Link></Button></div>:<div className="space-y-3">{orders.map(o=><Link key={o.id} to="/order/$id" params={{id:o.id}} className="surface-card flex flex-wrap items-center justify-between gap-4 rounded-2xl p-5 transition-transform hover:-translate-y-0.5"><div><p className="font-bold">#{o.order_number} · {o.service_name}</p><p className="text-muted-foreground mt-1 text-xs">{o.platform} · {dateAr(o.created_at)} · {num(o.quantity)} وحدة</p></div><div className="text-left"><p className="font-bold">{money(o.total_price)}</p><p className="text-muted-foreground text-xs">{o.status}</p></div></Link>)}</div>}</div></PageShell>}
