import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { Loader2,Save,UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader,PageShell } from "@/components/page-shell";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/dashboard/profile")({head:()=>({meta:[{title:"الملف الشخصي | ViralHub"}]}),component:ProfilePage});
function ProfilePage(){const[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);useEffect(()=>{let a=true;(async()=>{const{data}=await supabase.auth.getUser();if(!data.user){window.location.href="/login";return}const{data:p}=await supabase.from("profiles").select("display_name,email,phone").eq("id",data.user.id).maybeSingle();if(a){setName(p?.display_name??"");setPhone(p?.phone??"");setEmail(p?.email??data.user.email??"");setLoading(false)}})();return()=>{a=false}},[]);async function save(){const{data}=await supabase.auth.getUser();if(!data.user)return;setSaving(true);const{error}=await supabase.from("profiles").update({display_name:name.trim()||null,phone:phone.trim()||null}).eq("id",data.user.id);setSaving(false);if(error)toast.error(error.message);else toast.success("تم حفظ الملف الشخصي")};if(loading)return <PageShell><div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="animate-spin"/></div></PageShell>;return <PageShell><PageHeader eyebrow="حسابي" title="الملف الشخصي" description="حدّث بيانات حسابك."/><div className="mx-auto max-w-2xl px-4 py-10"><div className="surface-card rounded-2xl p-6"><UserRound className="text-primary mb-5 size-7"/><label className="text-sm font-bold">الاسم</label><Input className="mt-2" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/><label className="mt-4 block text-sm font-bold">البريد الإلكتروني</label><Input className="mt-2" value={email} disabled/><label className="mt-4 block text-sm font-bold">رقم الهاتف</label><Input className="mt-2" value={phone} onChange={e=>setPhone(e.target.value)} maxLength={30}/><Button className="mt-6 w-full" variant="hero" onClick={()=>void save()} disabled={saving}>{saving?<Loader2 className="animate-spin"/>:<Save/>} حفظ التغييرات</Button></div></div></PageShell>}
