/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as DashboardWalletTopupRouteImport } from './routes/dashboard.wallet.topup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletTopupRoute = DashboardWalletTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => DashboardWalletRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wallet': typeof DashboardWalletRouteWithChildren
  '/order/$id': typeof OrderIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/dashboard/wallet/topup': typeof DashboardWalletTopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wallet': typeof DashboardWalletRouteWithChildren
  '/order/$id': typeof OrderIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/dashboard/wallet/topup': typeof DashboardWalletTopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wallet': typeof DashboardWalletRouteWithChildren
  '/order/$id': typeof OrderIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/dashboard/wallet/topup': typeof DashboardWalletTopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/admin/audit'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/services'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/tickets'
    | '/dashboard/wallet'
    | '/order/$id'
    | '/services/$slug'
    | '/services/'
    | '/dashboard/wallet/topup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/admin/audit'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/services'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/tickets'
    | '/dashboard/wallet'
    | '/order/$id'
    | '/services/$slug'
    | '/services'
    | '/dashboard/wallet/topup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/admin/audit'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/services'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/tickets'
    | '/dashboard/wallet'
    | '/order/$id'
    | '/services/$slug'
    | '/services/'
    | '/dashboard/wallet/topup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  OrderIdRoute: typeof OrderIdRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet/topup': {
      id: '/dashboard/wallet/topup'
      path: '/topup'
      fullPath: '/dashboard/wallet/topup'
      preLoaderRoute: typeof DashboardWalletTopupRouteImport
      parentRoute: typeof DashboardWalletRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardWalletRouteChildren {
  DashboardWalletTopupRoute: typeof DashboardWalletTopupRoute
}

const DashboardWalletRouteChildren: DashboardWalletRouteChildren = {
  DashboardWalletTopupRoute: DashboardWalletTopupRoute,
}

const DashboardWalletRouteWithChildren = DashboardWalletRoute._addFileChildren(
  DashboardWalletRouteChildren,
)

interface DashboardRouteChildren {
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardWalletRoute: typeof DashboardWalletRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardWalletRoute: DashboardWalletRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  OrderIdRoute: OrderIdRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
